const TAGS = {
  POST: 'POST',
  COMMENT: 'COMMENT',
  GLOBAL_FEED: 'GLOBAL_FEED',
  OWN_FEED: 'OWN_FEED',
  FAVORITE_FEED: 'FAVORITE_FEED',
  PROFILE: 'PROFILE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};

export default TAGS;
